// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cit

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/cloudformation"
	"sync"
)

// Ensure, that CloudFormationInterfaceMock does implement CloudFormationInterface.
// If this is not the case, regenerate this file with moq.
var _ CloudFormationInterface = &CloudFormationInterfaceMock{}

// CloudFormationInterfaceMock is a mock implementation of CloudFormationInterface.
//
//     func TestSomethingThatUsesCloudFormationInterface(t *testing.T) {
//
//         // make and configure a mocked CloudFormationInterface
//         mockedCloudFormationInterface := &CloudFormationInterfaceMock{
//             DescribeStackResourcesFunc: func(ctx context.Context, params *cloudformation.DescribeStackResourcesInput, optFns ...func(*cloudformation.Options)) (*cloudformation.DescribeStackResourcesOutput, error) {
// 	               panic("mock out the DescribeStackResources method")
//             },
//             GetTemplateFunc: func(ctx context.Context, params *cloudformation.GetTemplateInput, optFns ...func(*cloudformation.Options)) (*cloudformation.GetTemplateOutput, error) {
// 	               panic("mock out the GetTemplate method")
//             },
//         }
//
//         // use mockedCloudFormationInterface in code that requires CloudFormationInterface
//         // and then make assertions.
//
//     }
type CloudFormationInterfaceMock struct {
	// DescribeStackResourcesFunc mocks the DescribeStackResources method.
	DescribeStackResourcesFunc func(ctx context.Context, params *cloudformation.DescribeStackResourcesInput, optFns ...func(*cloudformation.Options)) (*cloudformation.DescribeStackResourcesOutput, error)

	// GetTemplateFunc mocks the GetTemplate method.
	GetTemplateFunc func(ctx context.Context, params *cloudformation.GetTemplateInput, optFns ...func(*cloudformation.Options)) (*cloudformation.GetTemplateOutput, error)

	// calls tracks calls to the methods.
	calls struct {
		// DescribeStackResources holds details about calls to the DescribeStackResources method.
		DescribeStackResources []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *cloudformation.DescribeStackResourcesInput
			// OptFns is the optFns argument value.
			OptFns []func(*cloudformation.Options)
		}
		// GetTemplate holds details about calls to the GetTemplate method.
		GetTemplate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *cloudformation.GetTemplateInput
			// OptFns is the optFns argument value.
			OptFns []func(*cloudformation.Options)
		}
	}
	lockDescribeStackResources sync.RWMutex
	lockGetTemplate            sync.RWMutex
}

// DescribeStackResources calls DescribeStackResourcesFunc.
func (mock *CloudFormationInterfaceMock) DescribeStackResources(ctx context.Context, params *cloudformation.DescribeStackResourcesInput, optFns ...func(*cloudformation.Options)) (*cloudformation.DescribeStackResourcesOutput, error) {
	if mock.DescribeStackResourcesFunc == nil {
		panic("CloudFormationInterfaceMock.DescribeStackResourcesFunc: method is nil but CloudFormationInterface.DescribeStackResources was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *cloudformation.DescribeStackResourcesInput
		OptFns []func(*cloudformation.Options)
	}{
		Ctx:    ctx,
		Params: params,
		OptFns: optFns,
	}
	mock.lockDescribeStackResources.Lock()
	mock.calls.DescribeStackResources = append(mock.calls.DescribeStackResources, callInfo)
	mock.lockDescribeStackResources.Unlock()
	return mock.DescribeStackResourcesFunc(ctx, params, optFns...)
}

// DescribeStackResourcesCalls gets all the calls that were made to DescribeStackResources.
// Check the length with:
//     len(mockedCloudFormationInterface.DescribeStackResourcesCalls())
func (mock *CloudFormationInterfaceMock) DescribeStackResourcesCalls() []struct {
	Ctx    context.Context
	Params *cloudformation.DescribeStackResourcesInput
	OptFns []func(*cloudformation.Options)
} {
	var calls []struct {
		Ctx    context.Context
		Params *cloudformation.DescribeStackResourcesInput
		OptFns []func(*cloudformation.Options)
	}
	mock.lockDescribeStackResources.RLock()
	calls = mock.calls.DescribeStackResources
	mock.lockDescribeStackResources.RUnlock()
	return calls
}

// GetTemplate calls GetTemplateFunc.
func (mock *CloudFormationInterfaceMock) GetTemplate(ctx context.Context, params *cloudformation.GetTemplateInput, optFns ...func(*cloudformation.Options)) (*cloudformation.GetTemplateOutput, error) {
	if mock.GetTemplateFunc == nil {
		panic("CloudFormationInterfaceMock.GetTemplateFunc: method is nil but CloudFormationInterface.GetTemplate was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *cloudformation.GetTemplateInput
		OptFns []func(*cloudformation.Options)
	}{
		Ctx:    ctx,
		Params: params,
		OptFns: optFns,
	}
	mock.lockGetTemplate.Lock()
	mock.calls.GetTemplate = append(mock.calls.GetTemplate, callInfo)
	mock.lockGetTemplate.Unlock()
	return mock.GetTemplateFunc(ctx, params, optFns...)
}

// GetTemplateCalls gets all the calls that were made to GetTemplate.
// Check the length with:
//     len(mockedCloudFormationInterface.GetTemplateCalls())
func (mock *CloudFormationInterfaceMock) GetTemplateCalls() []struct {
	Ctx    context.Context
	Params *cloudformation.GetTemplateInput
	OptFns []func(*cloudformation.Options)
} {
	var calls []struct {
		Ctx    context.Context
		Params *cloudformation.GetTemplateInput
		OptFns []func(*cloudformation.Options)
	}
	mock.lockGetTemplate.RLock()
	calls = mock.calls.GetTemplate
	mock.lockGetTemplate.RUnlock()
	return calls
}
