# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  test:
    desc: Go test without aws access
    cmds:
      - go test -short -v

  generate:
    desc: Go generation
    cmds: 
      - go generate .
      - go generate services/ses